### ISSUE TITLE
backgroud color for stickbox

### ISSUE THREAD

**Issue by jenningsloy318** [lkoehl/typst-boxes#11]
Thank you very much for the library! It's wonderful and very useful.

can you please add the paramter to set the backgroud  color for stickbox, sometime I used other color theme may not very suitable to use yellow for stickbox

**Comment by Loewe1000** [comment]
Done!

**Comment by jenningsloy318** [comment]
i use 

```typst
#import "@preview/colorful-boxes:1.4.2": stickybox
#slide(composer: (2fr, 3fr))[
  #stickybox(
    rotation: -5deg,
    width: 100%,
    fill: rgb("#ffb6a6"),
  )[leaders need ]
```

but still get error 
```log

    ┌─ 7-rules-of-power.typ:169:4
    │
169 │     fill: rgb("#ffb6a6"),
    │     ^^^^^^^^^^^^^^^^^^^^
```
it show typst: unexpected argument: fill

**Comment by Loewe1000** [comment]
You need to use version 1.4.3. 🙂

**Comment by jenningsloy318** [comment]
maybe still not published to typst universe 
```
error: package not found (searched for @preview/colorful-boxes:1.4.3)
```

**Comment by lkoehl** [comment]
PR submitted for typst universe [here](https://github.com/typst/packages/pull/2294)

**Comment by mrfragger** [comment]
[package]
name = "charged-ieee"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Typst GmbH <https://typst.app>"]
license = "MIT-0"
description = "An IEEE-style paper template to publish at conferences and journals for Electrical Engineering, Computer Science, and Computer Engineering"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

this is the example
Typst package check / @preview/colorful-boxes:1.4.3

packages/preview/colorful-boxes/1.4.3/examples/outline-colorbox.typ#L1

This import should use the package specification, not a relative path.

import "../lib.typ": outline-colorbox, colorbox

So I think it's saying 
[package]
entrypoint ="lib.typ"
path = ".."

but path might have to be relative to the root so inside a folder
path = "library"
